engineStrict: true
overrides:
  fast-uri: 3.1.4
  immutable: 5.1.9
  js-yaml: 4.3.0
allowBuilds:
  '@parcel/watcher': true
  vue-demi: true
strictPeerDependencies: true
peerDependencyRules:
  allowedVersions:
    'openapi-typescript>typescript': '6'
onlyBuiltDependencies:
  - '@parcel/watcher'
